version: '3.7'
services:
  rmib-fe:
    image: rmib-fe
    build: .
    container_name: rmib-fe
    env_file:
      - ./.env
    restart: always
    ports:
      - '8200:3000'
    networks:
      - rmib-network

networks:
  rmib-network:
    name: rmib
    driver: bridge
