version: '3.7'

services:
  rmib-fe:
    build: .
    image: 'rmib-fe'
    container_name: rmib-fe
    restart: always
    env_file:
      - .env
    ports:
      - '3100:3000'
    networks:
      - rmib
