version: '3.7'
services:
  artajasa-fe:
    build: .
    image: 'artajasa-fe'
    container_name: svc-artajasa-fe
    restart: always
    env_file:
      - ./.env
    ports:
      - '3100:3000'
    networks:
      - rmib

networks:
  rmibl:
    name: rmib
    external: true
