version: '3.7'
services:
  rmib-fe:
    build: .
    image: 'rmib-fe'
    container_name: svc-rmib-fe
    restart: always
    env_file:
      - ./.env
    ports:
      - '3000:3000'
    networks:
      - rmib

networks:
  rmib:
    name: rmib
    external: true
